// ParanoidNetwork API v0.3.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        (unknown)
// source: paranoid/paranoidnetwork/v1/paranoid.proto

package paranoidnetwork

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescGZIP(), []int{1}
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip         string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`                                   // required
	Port       string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`                               // required
	CommonName string `protobuf:"bytes,3,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"` // required
	Uuid       string `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`                               // required
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Node) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Node) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *Node) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type JoinClusterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip           string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`                                         // required
	Port         string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`                                     // required
	CommonName   string `protobuf:"bytes,3,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`       // required
	Uuid         string `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`                                     // required
	PoolPassword string `protobuf:"bytes,5,opt,name=pool_password,json=poolPassword,proto3" json:"pool_password,omitempty"` // optional
}

func (x *JoinClusterRequest) Reset() {
	*x = JoinClusterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterRequest) ProtoMessage() {}

func (x *JoinClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterRequest.ProtoReflect.Descriptor instead.
func (*JoinClusterRequest) Descriptor() ([]byte, []int) {
	return file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescGZIP(), []int{3}
}

func (x *JoinClusterRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *JoinClusterRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *JoinClusterRequest) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *JoinClusterRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *JoinClusterRequest) GetPoolPassword() string {
	if x != nil {
		return x.PoolPassword
	}
	return ""
}

type JoinClusterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JoinClusterResponse) Reset() {
	*x = JoinClusterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterResponse) ProtoMessage() {}

func (x *JoinClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterResponse.ProtoReflect.Descriptor instead.
func (*JoinClusterResponse) Descriptor() ([]byte, []int) {
	return file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescGZIP(), []int{4}
}

type NewGenerationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestingNode *Node  `protobuf:"bytes,1,opt,name=requesting_node,json=requestingNode,proto3" json:"requesting_node,omitempty"` // required
	PoolPassword   string `protobuf:"bytes,2,opt,name=pool_password,json=poolPassword,proto3" json:"pool_password,omitempty"`       // required
}

func (x *NewGenerationRequest) Reset() {
	*x = NewGenerationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGenerationRequest) ProtoMessage() {}

func (x *NewGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGenerationRequest.ProtoReflect.Descriptor instead.
func (*NewGenerationRequest) Descriptor() ([]byte, []int) {
	return file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescGZIP(), []int{5}
}

func (x *NewGenerationRequest) GetRequestingNode() *Node {
	if x != nil {
		return x.RequestingNode
	}
	return nil
}

func (x *NewGenerationRequest) GetPoolPassword() string {
	if x != nil {
		return x.PoolPassword
	}
	return ""
}

type NewGenerationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GenerationNumber int64    `protobuf:"varint,1,opt,name=generation_number,json=generationNumber,proto3" json:"generation_number,omitempty"` // required
	Peers            []string `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`                                                // required
}

func (x *NewGenerationResponse) Reset() {
	*x = NewGenerationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGenerationResponse) ProtoMessage() {}

func (x *NewGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGenerationResponse.ProtoReflect.Descriptor instead.
func (*NewGenerationResponse) Descriptor() ([]byte, []int) {
	return file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescGZIP(), []int{6}
}

func (x *NewGenerationResponse) GetGenerationNumber() int64 {
	if x != nil {
		return x.GenerationNumber
	}
	return 0
}

func (x *NewGenerationResponse) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

type SendKeyPieceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        *KeyPiece `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                                  // required
	AddElement bool      `protobuf:"varint,2,opt,name=add_element,json=addElement,proto3" json:"add_element,omitempty"` // required
}

func (x *SendKeyPieceRequest) Reset() {
	*x = SendKeyPieceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendKeyPieceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeyPieceRequest) ProtoMessage() {}

func (x *SendKeyPieceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeyPieceRequest.ProtoReflect.Descriptor instead.
func (*SendKeyPieceRequest) Descriptor() ([]byte, []int) {
	return file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescGZIP(), []int{7}
}

func (x *SendKeyPieceRequest) GetKey() *KeyPiece {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SendKeyPieceRequest) GetAddElement() bool {
	if x != nil {
		return x.AddElement
	}
	return false
}

type SendKeyPieceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientMustCommit bool `protobuf:"varint,1,opt,name=client_must_commit,json=clientMustCommit,proto3" json:"client_must_commit,omitempty"` // required
}

func (x *SendKeyPieceResponse) Reset() {
	*x = SendKeyPieceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendKeyPieceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeyPieceResponse) ProtoMessage() {}

func (x *SendKeyPieceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeyPieceResponse.ProtoReflect.Descriptor instead.
func (*SendKeyPieceResponse) Descriptor() ([]byte, []int) {
	return file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescGZIP(), []int{8}
}

func (x *SendKeyPieceResponse) GetClientMustCommit() bool {
	if x != nil {
		return x.ClientMustCommit
	}
	return false
}

type RequestKeyPieceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node       *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`              // required
	Generation int64 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"` // required
}

func (x *RequestKeyPieceRequest) Reset() {
	*x = RequestKeyPieceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestKeyPieceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestKeyPieceRequest) ProtoMessage() {}

func (x *RequestKeyPieceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestKeyPieceRequest.ProtoReflect.Descriptor instead.
func (*RequestKeyPieceRequest) Descriptor() ([]byte, []int) {
	return file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescGZIP(), []int{9}
}

func (x *RequestKeyPieceRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *RequestKeyPieceRequest) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type RequestKeyPieceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *KeyPiece `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // required
}

func (x *RequestKeyPieceResponse) Reset() {
	*x = RequestKeyPieceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestKeyPieceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestKeyPieceResponse) ProtoMessage() {}

func (x *RequestKeyPieceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestKeyPieceResponse.ProtoReflect.Descriptor instead.
func (*RequestKeyPieceResponse) Descriptor() ([]byte, []int) {
	return file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescGZIP(), []int{10}
}

func (x *RequestKeyPieceResponse) GetKey() *KeyPiece {
	if x != nil {
		return x.Key
	}
	return nil
}

type KeyPiece struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data              []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                                                    // required
	ParentFingerprint []byte `protobuf:"bytes,2,opt,name=parent_fingerprint,json=parentFingerprint,proto3" json:"parent_fingerprint,omitempty"` // required
	Prime             []byte `protobuf:"bytes,3,opt,name=prime,proto3" json:"prime,omitempty"`                                                  // required
	Seq               int64  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`                                                     // required
	// The Node data for the node who owns this KeyPiece
	OwnerNode *Node `protobuf:"bytes,5,opt,name=owner_node,json=ownerNode,proto3" json:"owner_node,omitempty"` // required
	// The KeyStateMachine generation this key belongs to
	Generation int64 `protobuf:"varint,6,opt,name=generation,proto3" json:"generation,omitempty"` // required
}

func (x *KeyPiece) Reset() {
	*x = KeyPiece{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPiece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPiece) ProtoMessage() {}

func (x *KeyPiece) ProtoReflect() protoreflect.Message {
	mi := &file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPiece.ProtoReflect.Descriptor instead.
func (*KeyPiece) Descriptor() ([]byte, []int) {
	return file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescGZIP(), []int{11}
}

func (x *KeyPiece) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *KeyPiece) GetParentFingerprint() []byte {
	if x != nil {
		return x.ParentFingerprint
	}
	return nil
}

func (x *KeyPiece) GetPrime() []byte {
	if x != nil {
		return x.Prime
	}
	return nil
}

func (x *KeyPiece) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *KeyPiece) GetOwnerNode() *Node {
	if x != nil {
		return x.OwnerNode
	}
	return nil
}

func (x *KeyPiece) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

var File_paranoid_paranoidnetwork_v1_paranoid_proto protoreflect.FileDescriptor

var file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2f, 0x70, 0x61, 0x72, 0x61, 0x6e,
	0x6f, 0x69, 0x64, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61,
	0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x70, 0x61,
	0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x22, 0x44, 0x0a, 0x0b, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69,
	0x64, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22,
	0x0e, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x5f, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x22, 0x92, 0x01, 0x0a, 0x12, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6f, 0x6f, 0x6c, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x87, 0x01, 0x0a,
	0x14, 0x4e, 0x65, 0x77, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4a, 0x0a, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f,
	0x69, 0x64, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6f, 0x6f, 0x6c, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x5a, 0x0a, 0x15, 0x4e, 0x65, 0x77, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2b, 0x0a, 0x11, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x65, 0x65,
	0x72, 0x73, 0x22, 0x6f, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x50, 0x69, 0x65,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69,
	0x64, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x69, 0x65, 0x63, 0x65, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x64, 0x64, 0x5f, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x64, 0x64, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x22, 0x44, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x50, 0x69,
	0x65, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x75, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x75, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x22, 0x6f, 0x0a, 0x16, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x50, 0x69, 0x65, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x61, 0x72,
	0x61, 0x6e, 0x6f, 0x69, 0x64, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x52, 0x0a, 0x17, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x50, 0x69, 0x65, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x61,
	0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x31,
	0x2e, 0x4b, 0x65, 0x79, 0x50, 0x69, 0x65, 0x63, 0x65, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0xd7,
	0x01, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x50, 0x69, 0x65, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x2d, 0x0a, 0x12, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72,
	0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x40, 0x0a, 0x0a, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f,
	0x6e, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x61, 0x72,
	0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xda, 0x04, 0x0a, 0x16, 0x50, 0x61, 0x72,
	0x61, 0x6e, 0x6f, 0x69, 0x64, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x28, 0x2e, 0x70, 0x61,
	0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64,
	0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x72, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x2f, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e,
	0x6f, 0x69, 0x64, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f,
	0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x30, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x61, 0x72, 0x61,
	0x6e, 0x6f, 0x69, 0x64, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4a,
	0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x78, 0x0a, 0x0d, 0x4e, 0x65, 0x77, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64,
	0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e,
	0x6f, 0x69, 0x64, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x75,
	0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x50, 0x69, 0x65, 0x63, 0x65, 0x12, 0x30,
	0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f,
	0x69, 0x64, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x4b, 0x65, 0x79, 0x50, 0x69, 0x65, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x31, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x61, 0x72, 0x61,
	0x6e, 0x6f, 0x69, 0x64, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x50, 0x69, 0x65, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7e, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x4b, 0x65, 0x79, 0x50, 0x69, 0x65, 0x63, 0x65, 0x12, 0x33, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e,
	0x6f, 0x69, 0x64, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4b, 0x65,
	0x79, 0x50, 0x69, 0x65, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e,
	0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69,
	0x64, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x50, 0x69, 0x65, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x53, 0x5a, 0x51, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x70, 0x73, 0x73, 0x64, 0x2d, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x70, 0x61, 0x72, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2f, 0x70, 0x61, 0x72, 0x61, 0x6e,
	0x6f, 0x69, 0x64, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x3b, 0x70, 0x61, 0x72, 0x61, 0x6e,
	0x6f, 0x69, 0x64, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescOnce sync.Once
	file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescData = file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDesc
)

func file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescGZIP() []byte {
	file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescOnce.Do(func() {
		file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescData = protoimpl.X.CompressGZIP(file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescData)
	})
	return file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDescData
}

var file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_paranoid_paranoidnetwork_v1_paranoid_proto_goTypes = []interface{}{
	(*PingRequest)(nil),             // 0: paranoid.paranoidnetwork.v1.PingRequest
	(*PingResponse)(nil),            // 1: paranoid.paranoidnetwork.v1.PingResponse
	(*Node)(nil),                    // 2: paranoid.paranoidnetwork.v1.Node
	(*JoinClusterRequest)(nil),      // 3: paranoid.paranoidnetwork.v1.JoinClusterRequest
	(*JoinClusterResponse)(nil),     // 4: paranoid.paranoidnetwork.v1.JoinClusterResponse
	(*NewGenerationRequest)(nil),    // 5: paranoid.paranoidnetwork.v1.NewGenerationRequest
	(*NewGenerationResponse)(nil),   // 6: paranoid.paranoidnetwork.v1.NewGenerationResponse
	(*SendKeyPieceRequest)(nil),     // 7: paranoid.paranoidnetwork.v1.SendKeyPieceRequest
	(*SendKeyPieceResponse)(nil),    // 8: paranoid.paranoidnetwork.v1.SendKeyPieceResponse
	(*RequestKeyPieceRequest)(nil),  // 9: paranoid.paranoidnetwork.v1.RequestKeyPieceRequest
	(*RequestKeyPieceResponse)(nil), // 10: paranoid.paranoidnetwork.v1.RequestKeyPieceResponse
	(*KeyPiece)(nil),                // 11: paranoid.paranoidnetwork.v1.KeyPiece
}
var file_paranoid_paranoidnetwork_v1_paranoid_proto_depIdxs = []int32{
	2,  // 0: paranoid.paranoidnetwork.v1.PingRequest.node:type_name -> paranoid.paranoidnetwork.v1.Node
	2,  // 1: paranoid.paranoidnetwork.v1.NewGenerationRequest.requesting_node:type_name -> paranoid.paranoidnetwork.v1.Node
	11, // 2: paranoid.paranoidnetwork.v1.SendKeyPieceRequest.key:type_name -> paranoid.paranoidnetwork.v1.KeyPiece
	2,  // 3: paranoid.paranoidnetwork.v1.RequestKeyPieceRequest.node:type_name -> paranoid.paranoidnetwork.v1.Node
	11, // 4: paranoid.paranoidnetwork.v1.RequestKeyPieceResponse.key:type_name -> paranoid.paranoidnetwork.v1.KeyPiece
	2,  // 5: paranoid.paranoidnetwork.v1.KeyPiece.owner_node:type_name -> paranoid.paranoidnetwork.v1.Node
	0,  // 6: paranoid.paranoidnetwork.v1.ParanoidNetworkService.Ping:input_type -> paranoid.paranoidnetwork.v1.PingRequest
	3,  // 7: paranoid.paranoidnetwork.v1.ParanoidNetworkService.JoinCluster:input_type -> paranoid.paranoidnetwork.v1.JoinClusterRequest
	5,  // 8: paranoid.paranoidnetwork.v1.ParanoidNetworkService.NewGeneration:input_type -> paranoid.paranoidnetwork.v1.NewGenerationRequest
	7,  // 9: paranoid.paranoidnetwork.v1.ParanoidNetworkService.SendKeyPiece:input_type -> paranoid.paranoidnetwork.v1.SendKeyPieceRequest
	9,  // 10: paranoid.paranoidnetwork.v1.ParanoidNetworkService.RequestKeyPiece:input_type -> paranoid.paranoidnetwork.v1.RequestKeyPieceRequest
	1,  // 11: paranoid.paranoidnetwork.v1.ParanoidNetworkService.Ping:output_type -> paranoid.paranoidnetwork.v1.PingResponse
	4,  // 12: paranoid.paranoidnetwork.v1.ParanoidNetworkService.JoinCluster:output_type -> paranoid.paranoidnetwork.v1.JoinClusterResponse
	6,  // 13: paranoid.paranoidnetwork.v1.ParanoidNetworkService.NewGeneration:output_type -> paranoid.paranoidnetwork.v1.NewGenerationResponse
	8,  // 14: paranoid.paranoidnetwork.v1.ParanoidNetworkService.SendKeyPiece:output_type -> paranoid.paranoidnetwork.v1.SendKeyPieceResponse
	10, // 15: paranoid.paranoidnetwork.v1.ParanoidNetworkService.RequestKeyPiece:output_type -> paranoid.paranoidnetwork.v1.RequestKeyPieceResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_paranoid_paranoidnetwork_v1_paranoid_proto_init() }
func file_paranoid_paranoidnetwork_v1_paranoid_proto_init() {
	if File_paranoid_paranoidnetwork_v1_paranoid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinClusterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinClusterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewGenerationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewGenerationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendKeyPieceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendKeyPieceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestKeyPieceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestKeyPieceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPiece); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paranoid_paranoidnetwork_v1_paranoid_proto_goTypes,
		DependencyIndexes: file_paranoid_paranoidnetwork_v1_paranoid_proto_depIdxs,
		MessageInfos:      file_paranoid_paranoidnetwork_v1_paranoid_proto_msgTypes,
	}.Build()
	File_paranoid_paranoidnetwork_v1_paranoid_proto = out.File
	file_paranoid_paranoidnetwork_v1_paranoid_proto_rawDesc = nil
	file_paranoid_paranoidnetwork_v1_paranoid_proto_goTypes = nil
	file_paranoid_paranoidnetwork_v1_paranoid_proto_depIdxs = nil
}
