// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discoverynetwork/discovery.proto

package discoverynetwork

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyMessage) Reset()         { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()    {}
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_622584ca8432c7d7, []int{0}
}
func (m *EmptyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMessage.Unmarshal(m, b)
}
func (m *EmptyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMessage.Marshal(b, m, deterministic)
}
func (dst *EmptyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMessage.Merge(dst, src)
}
func (m *EmptyMessage) XXX_Size() int {
	return xxx_messageInfo_EmptyMessage.Size(m)
}
func (m *EmptyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMessage proto.InternalMessageInfo

type DisconnectRequest struct {
	Pool                 string   `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Node                 *Node    `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectRequest) Reset()         { *m = DisconnectRequest{} }
func (m *DisconnectRequest) String() string { return proto.CompactTextString(m) }
func (*DisconnectRequest) ProtoMessage()    {}
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_622584ca8432c7d7, []int{1}
}
func (m *DisconnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectRequest.Unmarshal(m, b)
}
func (m *DisconnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectRequest.Marshal(b, m, deterministic)
}
func (dst *DisconnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectRequest.Merge(dst, src)
}
func (m *DisconnectRequest) XXX_Size() int {
	return xxx_messageInfo_DisconnectRequest.Size(m)
}
func (m *DisconnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectRequest proto.InternalMessageInfo

func (m *DisconnectRequest) GetPool() string {
	if m != nil {
		return m.Pool
	}
	return ""
}

func (m *DisconnectRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DisconnectRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type JoinRequest struct {
	Pool                 string   `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Node                 *Node    `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_622584ca8432c7d7, []int{2}
}
func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (dst *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(dst, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetPool() string {
	if m != nil {
		return m.Pool
	}
	return ""
}

func (m *JoinRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *JoinRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type JoinResponse struct {
	// The time after which the server will remove the node from the list
	// if the node doesn't make the Renew RPC call
	ResetInterval        int64    `protobuf:"varint,1,opt,name=reset_interval,json=resetInterval,proto3" json:"reset_interval,omitempty"`
	Nodes                []*Node  `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_622584ca8432c7d7, []int{3}
}
func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (dst *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(dst, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetResetInterval() int64 {
	if m != nil {
		return m.ResetInterval
	}
	return 0
}

func (m *JoinResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Node struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	CommonName           string   `protobuf:"bytes,3,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	Uuid                 string   `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_622584ca8432c7d7, []int{4}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Node) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Node) GetCommonName() string {
	if m != nil {
		return m.CommonName
	}
	return ""
}

func (m *Node) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "discoverynetwork.EmptyMessage")
	proto.RegisterType((*DisconnectRequest)(nil), "discoverynetwork.DisconnectRequest")
	proto.RegisterType((*JoinRequest)(nil), "discoverynetwork.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "discoverynetwork.JoinResponse")
	proto.RegisterType((*Node)(nil), "discoverynetwork.Node")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiscoveryNetworkClient is the client API for DiscoveryNetwork service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscoveryNetworkClient interface {
	// Discovery Calls
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type discoveryNetworkClient struct {
	cc *grpc.ClientConn
}

func NewDiscoveryNetworkClient(cc *grpc.ClientConn) DiscoveryNetworkClient {
	return &discoveryNetworkClient{cc}
}

func (c *discoveryNetworkClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, "/discoverynetwork.DiscoveryNetwork/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryNetworkClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/discoverynetwork.DiscoveryNetwork/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryNetworkServer is the server API for DiscoveryNetwork service.
type DiscoveryNetworkServer interface {
	// Discovery Calls
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	Disconnect(context.Context, *DisconnectRequest) (*EmptyMessage, error)
}

func RegisterDiscoveryNetworkServer(s *grpc.Server, srv DiscoveryNetworkServer) {
	s.RegisterService(&_DiscoveryNetwork_serviceDesc, srv)
}

func _DiscoveryNetwork_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryNetworkServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discoverynetwork.DiscoveryNetwork/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryNetworkServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryNetwork_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryNetworkServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discoverynetwork.DiscoveryNetwork/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryNetworkServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiscoveryNetwork_serviceDesc = grpc.ServiceDesc{
	ServiceName: "discoverynetwork.DiscoveryNetwork",
	HandlerType: (*DiscoveryNetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _DiscoveryNetwork_Join_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _DiscoveryNetwork_Disconnect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discoverynetwork/discovery.proto",
}

func init() {
	proto.RegisterFile("discoverynetwork/discovery.proto", fileDescriptor_discovery_622584ca8432c7d7)
}

var fileDescriptor_discovery_622584ca8432c7d7 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x52, 0xd1, 0x4a, 0xc3, 0x40,
	0x10, 0x6c, 0xd2, 0x28, 0x76, 0x5b, 0x4b, 0xdd, 0x07, 0x09, 0x05, 0x35, 0x44, 0x84, 0x22, 0x52,
	0xa1, 0xfe, 0x42, 0x45, 0x14, 0xec, 0x43, 0xfc, 0x80, 0x12, 0x93, 0x45, 0x0e, 0xcd, 0xed, 0x79,
	0x77, 0x6d, 0xe9, 0x5f, 0xf9, 0x89, 0x92, 0xbb, 0x5a, 0xb5, 0x55, 0x1f, 0x7d, 0xdb, 0x9d, 0xcc,
	0x66, 0x76, 0xf6, 0x06, 0x92, 0x52, 0x98, 0x82, 0xe7, 0xa4, 0x97, 0x92, 0xec, 0x82, 0xf5, 0xf3,
	0xe5, 0x1a, 0x18, 0x2a, 0xcd, 0x96, 0xb1, 0xb7, 0xc9, 0x48, 0xbb, 0xd0, 0xb9, 0xae, 0x94, 0x5d,
	0xde, 0x93, 0x31, 0xf9, 0x13, 0xa5, 0x0c, 0x07, 0xe3, 0x9a, 0x23, 0x25, 0x15, 0x36, 0xa3, 0xd7,
	0x19, 0x19, 0x8b, 0x08, 0x91, 0x62, 0x7e, 0x89, 0x83, 0x24, 0x18, 0xb4, 0x32, 0x57, 0x63, 0x1f,
	0xf6, 0x54, 0x6e, 0xcc, 0x82, 0x75, 0x19, 0x87, 0x0e, 0x5f, 0xf7, 0x78, 0x0e, 0x91, 0xe4, 0x92,
	0xe2, 0x66, 0x12, 0x0c, 0xda, 0xa3, 0xc3, 0xe1, 0xa6, 0xea, 0x70, 0xc2, 0x25, 0x65, 0x8e, 0x93,
	0x0a, 0x68, 0xdf, 0xb1, 0x90, 0xff, 0x21, 0x55, 0x40, 0xc7, 0x4b, 0x19, 0xc5, 0xd2, 0x10, 0x9e,
	0x41, 0x57, 0x93, 0x21, 0x3b, 0x15, 0xd2, 0x92, 0x9e, 0xe7, 0x5e, 0xb5, 0x99, 0xed, 0x3b, 0xf4,
	0x76, 0x05, 0xe2, 0x05, 0xec, 0xd4, 0xe3, 0x26, 0x0e, 0x93, 0xe6, 0x1f, 0x1a, 0x9e, 0x94, 0x4e,
	0x21, 0xaa, 0x5b, 0xec, 0x42, 0x28, 0xd4, 0xca, 0x46, 0x28, 0x94, 0x37, 0xa6, 0xed, 0xca, 0x80,
	0xab, 0xf1, 0x04, 0xda, 0x05, 0x57, 0x15, 0xcb, 0xa9, 0xcc, 0x2b, 0xef, 0xa1, 0x95, 0x81, 0x87,
	0x26, 0x79, 0x45, 0xf5, 0xd0, 0x6c, 0x26, 0xca, 0x38, 0xf2, 0x43, 0x75, 0x3d, 0x7a, 0x0b, 0xa0,
	0x37, 0xfe, 0xd8, 0x60, 0xe2, 0x37, 0xc0, 0x1b, 0x88, 0x6a, 0x6b, 0x78, 0xb4, 0xbd, 0xdc, 0x97,
	0xeb, 0xf6, 0x8f, 0x7f, 0xfb, 0xec, 0x2f, 0x92, 0x36, 0xf0, 0x01, 0xe0, 0xf3, 0xfd, 0xf1, 0x74,
	0x9b, 0xbf, 0x95, 0x8e, 0x9f, 0x7e, 0xfa, 0x2d, 0x52, 0x8d, 0xc7, 0x5d, 0x97, 0xbe, 0xab, 0xf7,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x68, 0xf6, 0x4b, 0x3a, 0xa1, 0x02, 0x00, 0x00,
}
